use serde::{Deserialize, Serialize};
use serde_json::Value;

pub const PROTOCOL_VERSION:u16=1;
#[derive(Debug,Clone,PartialEq,Serialize,Deserialize)]pub struct Envelope{pub version:u16,pub id:String,#[serde(rename="type")]pub message_type:MessageType,#[serde(skip_serializing_if="Option::is_none")]pub correlation_id:Option<String>,#[serde(skip_serializing_if="Option::is_none")]pub session_id:Option<String>,pub payload:Value}
impl Envelope{pub fn new(id:impl Into<String>,message_type:MessageType,payload:Value)->Self{Self{version:PROTOCOL_VERSION,id:id.into(),message_type,correlation_id:None,session_id:None,payload}}pub fn correlated_to(mut self,id:impl Into<String>)->Self{self.correlation_id=Some(id.into());self}pub fn in_session(mut self,id:impl Into<String>)->Self{self.session_id=Some(id.into());self}pub fn encode_json(&self)->Result<String,serde_json::Error>{serde_json::to_string(self)}pub fn decode_json(json:&str)->Result<Self,ProtocolError>{let envelope:Self=serde_json::from_str(json).map_err(ProtocolError::InvalidJson)?;if envelope.version!=PROTOCOL_VERSION{return Err(ProtocolError::UnsupportedVersion(envelope.version));}Ok(envelope)}}
#[derive(Debug,Clone,Copy,PartialEq,Eq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum MessageType{Hello,CapabilityAnnounce,DiscoveryRequest,DiscoveryResult,Command,CommandResult,Event,StateSnapshot,Error}
#[derive(Debug)]pub enum ProtocolError{InvalidJson(serde_json::Error),UnsupportedVersion(u16)}

#[cfg(test)]mod tests{use super::*;use serde_json::json;
#[test]fn envelope_round_trips_as_json(){let envelope=Envelope::new("evt-1",MessageType::Event,json!({"name":"vehicle.speed_changed","speed_kmh":90})).in_session("session-7");let json=envelope.encode_json().expect("encode envelope");let decoded=Envelope::decode_json(&json).expect("decode envelope");assert_eq!(decoded,envelope);}
#[test]fn wire_format_contains_an_explicit_version_and_type(){let envelope=Envelope::new("hello-1",MessageType::Hello,json!({"client":"dashboard"}));let value:Value=serde_json::from_str(&envelope.encode_json().unwrap()).unwrap();assert_eq!(value["version"],PROTOCOL_VERSION);assert_eq!(value["type"],"hello");assert!(value.get("correlation_id").is_none());}
#[test]fn discovery_message_types_have_stable_wire_names(){let request=Envelope::new("discover-1",MessageType::DiscoveryRequest,json!({}));let result=Envelope::new("discover-result-1",MessageType::DiscoveryResult,json!({}));let request:Value=serde_json::from_str(&request.encode_json().unwrap()).unwrap();let result:Value=serde_json::from_str(&result.encode_json().unwrap()).unwrap();assert_eq!(request["type"],"discovery_request");assert_eq!(result["type"],"discovery_result");}
#[test]fn command_result_can_be_correlated(){let envelope=Envelope::new("result-1",MessageType::CommandResult,json!({"outcome":"succeeded"})).correlated_to("cmd-42");let decoded=Envelope::decode_json(&envelope.encode_json().unwrap()).unwrap();assert_eq!(decoded.correlation_id.as_deref(),Some("cmd-42"));}
#[test]fn unsupported_protocol_version_is_rejected(){let json=r#"{"version":99,"id":"hello-1","type":"hello","payload":{}}"#;match Envelope::decode_json(json){Err(ProtocolError::UnsupportedVersion(99))=>{}other=>panic!("unexpected result: {other:?}")}}}
